require 'rake'

libsuffix = RbConfig::CONFIG['SOEXT']
minimap2_dir = File.expand_path('minimap2', __dir__)
target_dir = '../../vendor'
target_fname = "libminimap2.#{libsuffix}"
target_path = File.join(target_dir, target_fname)

task default: 'minimap2:build'

namespace :minimap2 do
  desc 'Compile Minimap2'
  task :build do
    Dir.chdir(minimap2_dir) do
      # Add -fPIC option to Makefile
      sh 'git apply ../minimap2.patch'
      sh 'cp ../cmappy/cmappy.h ../cmappy/cmappy.c .'
      sh 'make'
      case RbConfig::CONFIG['host_os']
      when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
        warn 'windows not supported'
      when /darwin|mac os/
        sh "clang -dynamiclib -undefined dynamic_lookup -o #{target_fname} *.o"
      else
        sh "cc -shared -o #{target_fname} *.o"
      end
      sh 'rm cmappy.h cmappy.c'
      sh 'git apply -R ../minimap2.patch'
      sh "mkdir -p #{target_dir}"
      sh "mv #{target_fname} #{target_path}"
    end
  end

  desc 'Cleanup'
  task :clean do
    Dir.chdir(minimap2_dir) do
      sh 'make clean'
      sh "rm #{target_path}" if File.exist?(target_path)
    end
  end
end
