name: CI

on:
- push
- pull_request

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
        ruby:
          - 2.7
          - 3.0
    runs-on: ${{ matrix.os }}-latest
    steps:
        
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
    
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake minimap2:compile
          bundle exec rake test
          